sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_packages:
  - reticulate
  - tensorflow
  - R6
  - coda
  - testthat
  - covr

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  - source travis_install.sh

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev

